# Import libraries
library(tidyverse)
library(shiny)
library(bslib)

# Load vocab
adjectives <- adjectives()
pronouns <- pronouns()
present_tense_verbs <- present_tense_verbs()
past_tense_verbs <- past_tense_verbs()
prepositions <- prepositions()
numbers <- numbers()
nouns_social <- nouns_social()
nouns_nominative <- nouns_nominative()
nouns_locative <- nouns_locative()
nouns_instrumental <- nouns_instrumental()
nouns_genitive <- nouns_genitive()
nouns_dative <- nouns_dative()
nouns_accusative <- nouns_accusative()
nouns_ablative <- nouns_ablative()
adverbs <- adverbs()
negative_mood_verbs <- negative_mood_verbs()
interrogatives_demonstratives <- interrogatives_demonstratives()
imperative_verbs_informal <- imperative_verbs_informal()
future_tense_verbs <- future_tense_verbs()
