future_tense_verbs <- list(
  c("I will buy", ""),
  c("You (informal) will buy", ""),
  c("He will buy", ""),
  c("She will buy", ""),
  c("They (singular formal) will  buy", ""),
  c("It will buy", ""),
  c("We will buy", ""),
  c("You (plural) will buy", ""),
  c("They (people) will buy", ""),
  c("They (objects) will buy", ""),
  c("I will look", ""),
  c("You (informal) will look", ""),
  c("He will look", ""),
  c("She will look", ""),
  c("They (singular formal) will look", ""),
  c("It will look", ""),
  c("We will look", ""),
  c("You (plural) will look", ""),
  c("They (people) will look", ""),
  c("They (objects) will look", ""),
  c("I will squeeze", ""),
  c("You (informal) will squeeze", ""),
  c("He will squeeze", ""),
  c("She will squeeze", ""),
  c("They (singular formal) will squeeze", ""),
  c("It will squeeze", ""),
  c("We will squeeze", ""),
  c("You (plural) will squeeze", ""),
  c("They (people) will squeeze", ""),
  c("They (objects) will squeeze", ""),
  c("I will be/sit", ""),
  c("You (informal) will be/sit", ""),
  c("He will be/sit", ""),
  c("She will be/sit", ""),
  c("They (singular formal) will be/sit", ""),
  c("It will be/sit", ""),
  c("We will be/sit", ""),
  c("You (plural) will be/sit", ""),
  c("They (people) will be/sit", ""),
  c("They (objects) will be/sit", ""),
  c("I will eat", ""),
  c("You (informal) will eat", ""),
  c("He will eat", ""),
  c("She will eat", ""),
  c("They (singular formal) will eat", ""),
  c("It will eat", ""),
  c("We will eat", ""),
  c("You (plural) will eat", ""),
  c("They (people) will eat", ""),
  c("They (objects) will eat", ""),
  c("I will sit", ""),
  c("You (informal) will sit", ""),
  c("He will sit", ""),
  c("She will sit", ""),
  c("They (singular formal) will sit", ""),
  c("It will sit", ""),
  c("We will sit", ""),
  c("You (plural) will sit", ""),
  c("They (people) will sit", ""),
  c("They (objects) will sit", ""),
  c("I will fall", ""),
  c("You (informal) will fall", ""),
  c("He will fall", ""),
  c("She will fall", ""),
  c("They (singular formal) fall", ""),
  c("It will fall", ""),
  c("We will fall", ""),
  c("You (plural) will fall", ""),
  c("They (people) will fall", ""),
  c("They (objects) will fall", ""),
  c("I will take", ""),
  c("You (informal) will take", ""),
  c("He will take", ""),
  c("She will take", ""),
  c("They (singular formal) will take", ""),
  c("It will take", ""),
  c("We will take", ""),
  c("You (plural) will take", ""),
  c("They (people) will take", ""),
  c("They (objects) will take", ""),
  c("I will kill", ""),
  c("You (informal) will kill", ""),
  c("He will kills", ""),
  c("She will kill", ""),
  c("They (singular formal) will kill", ""),
  c("It will kill", ""),
  c("We will kill", ""),
  c("You (plural) will kill", ""),
  c("They (people) will kill", ""),
  c("They (objects) will kill", ""),
  c("I will do", ""),
  c("You (informal) will do", ""),
  c("He will do", ""),
  c("She will do", ""),
  c("They (singular formal) will do", ""),
  c("It will do", ""),
  c("We will do", ""),
  c("You (plural) will do", ""),
  c("They (people) will do", ""),
  c("They (objects) will do", "")
)