future_tense_verbs <- list(
  c("I will buy", "வாங்குவேன்"),
  c("You (informal) will buy", "வாங்குவாய்"),
  c("He will buy", "வாங்குவான்"),
  c("She will buy", "வாங்குவாள்"),
  c("They (singular formal) will  buy", "வாங்குவார்"),
  c("It will buy", "வாங்குவது"),
  c("We will buy", "வாங்குவோம்"),
  c("You (plural) will buy", "வாங்குவீர்கள்"),
  c("They (people) will buy", "வாங்குவனர்"),
  c("They (objects) will buy", "வாங்குவன"),
  c("I will look", "பார்ப்பேன்"),
  c("You (informal) will look", "பார்ப்பாய்"),
  c("He will look", "பார்ப்பான்"),
  c("She will look", "பார்ப்பாள்"),
  c("They (singular formal) will look", "பார்ப்பார்"),
  c("It will look", "பார்ப்பது"),
  c("We will look", "பார்ப்போம்"),
  c("You (plural) will look", "பார்ப்பீர்கள்"),
  c("They (people) will look", "பார்ப்பனர்"),
  c("They (objects) will look", "பார்ப்பன"),
  c("I will squeeze", "பிழிவேன்"),
  c("You (informal) will squeeze", "பிழிவாய்"),
  c("He will squeeze", "பிழிவான்"),
  c("She will squeeze", "பிழிவாள்"),
  c("They (singular formal) will squeeze", "பிழிவார்"),
  c("It will squeeze", "பிழிவது"),
  c("We will squeeze", "பிழிவோம்"),
  c("You (plural) will squeeze", "பிழிவீர்கள்"),
  c("They (people) will squeeze", "பிழிவனர்"),
  c("They (objects) will squeeze", "பிழிவன"),
  c("I will be/sit", "இருப்பேன்"),
  c("You (informal) will be/sit", "இருப்பாய்"),
  c("He will be/sit", "இருப்பான்"),
  c("She will be/sit", "இருப்பாள்"),
  c("They (singular formal) will be/sit", "இருப்பார்"),
  c("It will be/sit", "இருப்பது"),
  c("We will be/sit", "இருப்போம்"),
  c("You (plural) will be/sit", "இருப்பீர்கள்"),
  c("They (people) will be/sit", "இருப்பனர்"),
  c("They (objects) will be/sit", "இருப்பன"),
  c("I will eat", "சாப்பிடுவேன்"),
  c("You (informal) will eat", "சாப்பிடுவாய்"),
  c("He will eat", "சாப்பிடுவான்"),
  c("She will eat", "சாப்பிடுவாள்"),
  c("They (singular formal) will eat", "சாப்பிடுவார்"),
  c("It will eat", "சாப்பிடுவது"),
  c("We will eat", "சாப்பிடுவோம்"),
  c("You (plural) will eat", "சாப்பிடுவீர்கள்"),
  c("They (people) will eat", "சாப்பிடுவனர்"),
  c("They (objects) will eat", "சாப்பிடுவன"),
  c("I will sit", "உட்கார்வேன்"),
  c("You (informal) will sit", "உட்கார்வாய்"),
  c("He will sit", "உட்கார்வான்"),
  c("She will sit", "உட்கார்வாள்"),
  c("They (singular formal) will sit", "உட்கார்வார்"),
  c("It will sit", "உட்கார்வது"),
  c("We will sit", "உட்கார்வோம்"),
  c("You (plural) will sit", "உட்கார்வீர்கள்"),
  c("They (people) will sit", "உட்கார்வனர்"),
  c("They (objects) will sit", "உட்கார்வன"),
  c("I will fall", "விழுவேன்"),
  c("You (informal) will fall", "விழுவாய்"),
  c("He will fall", "விழுவான்"),
  c("She will fall", "விழுவாள்"),
  c("They (singular formal) fall", "விழுவார்"),
  c("It will fall", "விழுவது"),
  c("We will fall", "விழுவோம்"),
  c("You (plural) will fall", "விழுவீர்கள்"),
  c("They (people) will fall", "விழுவனர்"),
  c("They (objects) will fall", "விழுவன"),
  c("I will take", "கொள்வேன்"),
  c("You (informal) will take", "கொள்வாய்"),
  c("He will take", "கொள்வான்"),
  c("She will take", "கொள்வாள்"),
  c("They (singular formal) will take", "கொள்வார்"),
  c("It will take", "கொள்வது"),
  c("We will take", "கொள்வோம்"),
  c("You (plural) will take", "கொள்வீர்கள்"),
  c("They (people) will take", "கொள்வனர்"),
  c("They (objects) will take", "கொள்வன"),
  c("I will kill", "கொல்வேன்"),
  c("You (informal) will kill", "கொல்வாய்"),
  c("He will kills", "கொல்வான்"),
  c("She will kill", "கொல்வாள்"),
  c("They (singular formal) will kill", "கொல்வார்"),
  c("It will kill", "கொல்வது"),
  c("We will kill", "கொல்வோம்"),
  c("You (plural) will kill", "கொல்வீர்கள்"),
  c("They (people) will kill", "கொல்வனர்"),
  c("They (objects) will kill", "கொல்வன"),
  c("I will do", "செய்வேன்"),
  c("You (informal) will do", "செய்வாய்"),
  c("He will do", "செய்வான்"),
  c("She will do", "செய்வாள்"),
  c("They (singular formal) will do", "செய்வார்"),
  c("It will do", "செய்வது"),
  c("We will do", "செய்வோம்"),
  c("You (plural) will do", "செய்வவீர்கள்"),
  c("They (people) will do", "செய்வனர்"),
  c("They (objects) will do", "செய்வன")
)