negative_mood_verbs <- list(
  c("I not do", ""),
  c("You (informal) not do", ""),
  c("He not do", ""),
  c("She not do", ""),
  c("They (singular formal) not do", ""),
  c("It not do", ""),
  c("We not do ", ""),
  c("You (plural) not do", ""),
  c("They (people) not do", ""),
  c("They (objects) not do", ""),
  c("I not walk", ""),
  c("You (informal) not walk", ""),
  c("He not walk", ""),
  c("She not walk", ""),
  c("They (singular formal) not walk", ""),
  c("It not walk", ""),
  c("We not walk", ""),
  c("You (plural) not walk", ""),
  c("They (people) not walk", ""),
  c("They (objects) not walk", ""),
  c("I not sleep", ""),
  c("You (informal) not sleep", ""),
  c("He not sleep", ""),
  c("She not sleep", ""),
  c("They (singular formal) not sleep", ""),
  c("It not sleep", ""),
  c("We not sleep", ""),
  c("You (plural) not sleep", ""),
  c("They (people) not sleep", ""),
  c("They (objects) not sleep", ""),
  c("I not come", ""),
  c("You (informal) not come", ""),
  c("He not come", ""),
  c("She not come", ""),
  c("They (singular formal) not come", ""),
  c("It not come", ""),
  c("We not come", ""),
  c("You (plural) not come", ""),
  c("They (people) not come", ""),
  c("They (objects) not come", ""),
  c("I not run", ""),
  c("You (informal) not run", ""),
  c("He not run", ""),
  c("She not run", ""),
  c("They (singular formal) not run", ""),
  c("It not run", ""),
  c("We not run", ""),
  c("You (plural) not run", ""),
  c("They (people) not run", ""),
  c("They (objects) not run", ""),
  c("I not eat", ""),
  c("You (informal) not eat", ""),
  c("He not eat", ""),
  c("She not eat", ""),
  c("They (singular formal) not eat", ""),
  c("It not eat", ""),
  c("We not eat", ""),
  c("You (plural) not eat", ""),
  c("They (people) not eat", ""),
  c("They (objects) not eat", "")
)