negative_mood_verbs <- list(
  c("I not do", "செய்யேன்"),
  c("You (informal) not do", "செய்யாய்"),
  c("He not do", "செய்யான்"),
  c("She not do", "செய்யாள்"),
  c("They (singular formal) not do", "செய்யார்"),
  c("It not do", "செய்யாது"),
  c("We not do ", "செய்யோம்"),
  c("You (plural) not do", "செய்யீர்கள்"),
  c("They (people) not do", "செய்யனர்"),
  c("They (objects) not do", "செய்யன"),
  c("I not walk", "நடவேன்"),
  c("You (informal) not walk", "நடவாய்"),
  c("He not walk", "நடவான்"),
  c("She not walk", "நடவாள்"),
  c("They (singular formal) not walk", "நடவார்"),
  c("It not walk", "நடக்காது"),
  c("We not walk", "நடவோம்"),
  c("You (plural) not walk", "நடவீர்கள்"),
  c("They (people) not walk", "நடவனர்"),
  c("They (objects) not walk", "நடவன"),
  c("I not sleep", "தூங்கேன்"),
  c("You (informal) not sleep", "தூங்காய்"),
  c("He not sleep", "தூங்கான்"),
  c("She not sleep", "தூங்காள்"),
  c("They (singular formal) not sleep", "தூங்கார்"),
  c("It not sleep", "தூங்காது"),
  c("We not sleep", "தூங்கோம்"),
  c("You (plural) not sleep", "தூங்கீர்கள்"),
  c("They (people) not sleep", "தூங்கனர்"),
  c("They (objects) not sleep", "தூங்கன"),
  c("I not come", "வரேன்"),
  c("You (informal) not come", "வராய்"),
  c("He not come", "வரான்"),
  c("She not come", "வராள்"),
  c("They (singular formal) not come", "வரார்"),
  c("It not come", "வராது"),
  c("We not come", "வரோம்"),
  c("You (plural) not come", "வரீர்கள்"),
  c("They (people) not come", "வரனர்"),
  c("They (objects) not come", "வரன"),
  c("I not run", "ஓடேன்"),
  c("You (informal) not run", "ஓடாய்"),
  c("He not run", "ஓடான்"),
  c("She not run", "ஓடாள்"),
  c("They (singular formal) not run", "ஓடார்"),
  c("It not run", "ஓடாது"),
  c("We not run", "ஓடோம்"),
  c("You (plural) not run", "ஓடீர்கள்"),
  c("They (people) not run", "ஓடனர்"),
  c("They (objects) not run", "ஓடன"),
  c("I not eat", "சாப்பிடேன்"),
  c("You (informal) not eat", "சாப்பிடாய்"),
  c("He not eat", "சாப்பிடான்"),
  c("She not eat", "சாப்பிடாள்"),
  c("They (singular formal) not eat", "சாப்பிடார்"),
  c("It not eat", "சாப்பிடாது"),
  c("We not eat", "சாப்பிடோம்"),
  c("You (plural) not eat", "சாப்பிடீர்கள்"),
  c("They (people) not eat", "சாப்பிடனர்"),
  c("They (objects) not eat", "சாப்பிடன")
) %>%
  map(~ {
    .x[1] = paste0("[Verbs in the Negative mood] ", .x[1]) # prepend question type
    .x
  })