nouns <- list(
  c("hello","வணக்கம்"), 
  c("cow", "மாடு"),
  c("picture; movie", "படம்"),
  c("tooth", "பல்"),
  c("stone", "கல்"),
  c("soil; dirt", "மண்"),
  c("sand", "மணல்"),
  c("son", "மகன்"),
  c("daughter", "மகள்"),
  c("tree", "மரம்"),
  c("sea", "கடல்"),
  c("debt; obligation", "கடன்"),
  c("fruit", "பழம்"),
  c("page; side", "பக்கம்"),
  c("fingernail; toenail", "நகம்"),
  c("mind; willingness", "மனம்"),
  c("smell; scent; wedding", "மணம்"),
  c("turmeric; yellow", "மஞ்சல்"),
  c("gold", "தங்கம்"),
  c("place; location", "இடம்"),
  c("world", "உலகம்"),
  c("village; city", "ஊர்"),
  c("parrot", "கிளி"),
  c("crow", "காகம்"),
  c("leg; quarter", "கால்"),
  c("foot (body part)", "பாதம்"),
  c("month", "மாதம்"),
  c("day", "நாள்"),
  c("man", "மனிதன்"),
  c("help", "உதவி"),
  c("path; way", "வழி"),
  c("pain; discomfort", "வலி"),
  c("entrance", "வாசல்"),
  c("student (male)", "மாணவன்"),
  c("student (female)", "மாணவி"),
  c("teacher", "ஆசிரியர்"),
  c("back (spine)", "முதுகு"),
  c("goat", "ஆடு"),
  c("thread; book", "நூல்"),
  c("crowd", "கூட்டம்"),
  c("book", "புத்தகம்"),
  c("piece; towel", "துண்டு"),
  c("cloud", "மேகம்"),
  c("morning", "காலை"),
  c("evening; afternoon; garland", "மாலை"),
  c("hand", "கை"),
  c("ink; mascara", "மை"),
  c("bag", "பை"),
  c("banana", "வாழை"),
  c("sari", "சேலை"),
  c("palm tree", "பனை"),
  c("pot", "பானை"),
  c("elephant", "யானை"),
  c("horse", "குதிரை"),
  c("leaf", "இலை"),
  c("shell", "ஓடு"),
  c("bracelet", "வளையல்"),
  c("step", "படி"),
  c("bottom", "அடி"),
  c("baby; child", "குழந்தை"),
  c("drawn line", "கோடு"),
  c("written line; tax", "வரி"),
  c("skin; peel", "தோல்"),
  c("shoulder", "தோள்"),
  c("bud", "மொட்டு"),
  c("flower", "பூ"),
  c("silence", "மௌனம்"),
  c("bat (animal)", "வௌவால்"),
  c("what", "என்ன"),
  c("who (male)", "எவன்"),
  c("who (female)", "எவள்"),
  c("who (pl/ formal)", "எவர்"),
  c("why", "ஏன்"),
  c("which (sg)", "எது"),
  c("which (pl)", "எவை"),
  c("which (of many)", "எந்த"),
  c("that", "அந்த"),
  c("this", "இந்த"),
  c("where", "எங்கே"),
  c("there", "அங்கே"),
  c("here", "இங்கே"),
  c("when", "எப்போது"),
  c("then", "அப்போது"),
  c("now", "இப்போது"),
  c("how", "எப்படி"),
  c("this way", "இப்படி"),
  c("how many", "எத்தனை"),
  c("this much", "இவ்வளவு"),
  c("for what", "எதற்கு"),
  c("for that", "அதற்கு"),
  c("which day", "என்று"),
  c("that day", "அன்று"),
  c("yesterday", "நேற்று"),
  c("today", "இன்று"),
  c("tomorrow", "நாளை")
)