nouns_nominative <- list(
  c("hello","வணக்கம்"), 
  c("cow", "மாடு"),
  c("picture; movie", "படம்"),
  c("tooth", "பல்"),
  c("stone", "கல்"),
  c("soil; dirt", "மண்"),
  c("sand", "மணல்"),
  c("son", "மகன்"),
  c("daughter", "மகள்"),
  c("tree", "மரம்"),
  c("sea", "கடல்"),
  c("debt; obligation", "கடன்"),
  c("fruit", "பழம்"),
  c("page; side", "பக்கம்"),
  c("fingernail; toenail", "நகம்"),
  c("mind; willingness", "மனம்"),
  c("smell; scent; wedding", "மணம்"),
  c("turmeric; yellow", "மஞ்சல்"),
  c("gold", "தங்கம்"),
  c("place; location", "இடம்"),
  c("world", "உலகம்"),
  c("village; city", "ஊர்"),
  c("parrot", "கிளி"),
  c("crow", "காகம்"),
  c("leg; quarter", "கால்"),
  c("foot (body part)", "பாதம்"),
  c("month", "மாதம்"),
  c("day", "நாள்"),
  c("man", "மனிதன்"),
  c("help", "உதவி"),
  c("path; way", "வழி"),
  c("pain; discomfort", "வலி"),
  c("entrance", "வாசல்"),
  c("student (male)", "மாணவன்"),
  c("student (female)", "மாணவி"),
  c("teacher", "ஆசிரியர்"),
  c("back (spine)", "முதுகு"),
  c("goat", "ஆடு"),
  c("thread; book", "நூல்"),
  c("crowd", "கூட்டம்"),
  c("book", "புத்தகம்"),
  c("piece; towel", "துண்டு"),
  c("cloud", "மேகம்"),
  c("morning", "காலை"),
  c("evening; afternoon; garland", "மாலை"),
  c("hand", "கை"),
  c("ink; mascara", "மை"),
  c("bag", "பை"),
  c("banana", "வாழை"),
  c("sari", "சேலை"),
  c("palm tree", "பனை"),
  c("pot", "பானை"),
  c("elephant", "யானை"),
  c("horse", "குதிரை"),
  c("leaf", "இலை"),
  c("shell", "ஓடு"),
  c("bracelet", "வளையல்"),
  c("step", "படி"),
  c("bottom", "அடி"),
  c("baby; child", "குழந்தை"),
  c("drawn line", "கோடு"),
  c("written line; tax", "வரி"),
  c("skin; peel", "தோல்"),
  c("shoulder", "தோள்"),
  c("bud", "மொட்டு"),
  c("flower", "பூ"),
  c("silence", "மௌனம்"),
  c("bat (animal)", "வௌவால்"),
  c("that day", "அன்று"),
  c("yesterday", "நேற்று"),
  c("today", "இன்று"),
  c("tomorrow", "நாளை"),
  c("milk", "பால்"),
  c("dog", "தாய்"),
  c("cat", "பூனை"),
  c("knife", "கத்தி"),
  c("wagon; bus; train", "வண்டி"),
  c("capital city", "தவைநகரம்"),
  c("door", "கதவு"),
  c("grass", "புல்"),
  c("eye", "கண்"),
  c("house; home", "வீடு"),
  c("spring, coil; bow (for arrows)", "வில்"),
  c("food", "சாப்பாடு"),
  c("water", "தண்ணீர்"),
  c("clock", "கடிகாரம்"),
  c("grass", "புல்"),
  c("money", "பணம்"),
  c("plant (noun)", "செடி"),
  c("distance", "தூரம்"),
  c("nuts", "கடலை"),
  c("box", "பெட்டி"),
  c("crown", "சூட்டு"),
  c("lullaby", "தாலாட்டு"),
  c("medicine", "மருந்து"),
  c("word", "வார்த்தை"),
  c("lie (untruth)", "பொய்"),
  c("candy", "மிட்டாய்"),
  c("people", "மக்கள்"),
  c("letter", "கடிதம்"),
  c("shop; store", "கடை"),
  c("goods; stuff", "சாமான்"),
  c("rain", "மழை"),
  c("school", "பள்ளி"),
  c("wife", "மனைவி"),
  c("body", "உடல்"),
  c("exercise", "பயிற்சி"),
  c("game", "விளையாட்டு"),
  c("thief", "திருடன்"),
  c("head", "தலை"),
  c("chief; leader", "தலைவர்"),
  c("job; task", "வேலை"),
  c("wedding", "கல்யாணம்")
) %>%
  map(~ {
    .x[1] = paste0("[Nouns in the Nominative case] ", .x[1]) # prepend question type
    .x
  })