past_tense_verbs <- list(
  c("I bought", ""),
  c("You (informal) bought", ""),
  c("He bought", ""),
  c("She bought", ""),
  c("They (singular formal) bought", ""),
  c("It bought", ""),
  c("We bought", ""),
  c("You (plural) bought", ""),
  c("They (people) bought", ""),
  c("They (objects) bought", ""),
  c("I looked", ""),
  c("You (informal) looked", ""),
  c("He looked", ""),
  c("She looked", ""),
  c("They (singular formal) looked", ""),
  c("It looked", ""),
  c("We looked", ""),
  c("You (plural) looked", ""),
  c("They (people) looked", ""),
  c("They (objects) looked", ""),
  c("I squeezed", ""),
  c("You (informal) squeezed", ""),
  c("He squeezed", ""),
  c("She squeezed", ""),
  c("They (singular formal) squeezed", ""),
  c("It squeezed", ""),
  c("We squeezed", ""),
  c("You (plural) squeezed", ""),
  c("They (people) squeezed", ""),
  c("They (objects) squeezed", ""),
  c("I was/sat", ""),
  c("You (informal) were/sat", ""),
  c("He was/sat", ""),
  c("She was/sat", ""),
  c("They (singular formal) were/sat", ""),
  c("It was/sat", ""),
  c("We were/sat", ""),
  c("You (plural) were/sat", ""),
  c("They (people) were/sat", ""),
  c("They (objects) were/sat", ""),
  c("I ate", ""),
  c("You (informal) ate", ""),
  c("He ate", ""),
  c("She ate", ""),
  c("They (singular formal) ate", ""),
  c("It ate", ""),
  c("We ate", ""),
  c("You (plural) ate", ""),
  c("They (people) ate", ""),
  c("They (objects) ate", ""),
  c("I sat", ""),
  c("You (informal) sat", ""),
  c("He sat", ""),
  c("She sat", ""),
  c("They (singular formal) sat", ""),
  c("It sat", ""),
  c("We sat", ""),
  c("You (plural) sat", ""),
  c("They (people) sat", ""),
  c("They (objects) sat", ""),
  c("I fell", ""),
  c("You (informal) fell", ""),
  c("He fell", ""),
  c("She fell", ""),
  c("They (singular formal) fell", ""),
  c("It fell", ""),
  c("We fell", ""),
  c("You (plural) fell", ""),
  c("They (people) fell", ""),
  c("They (objects) fell", ""),
  c("I took", ""),
  c("You (informal) took", ""),
  c("He took", ""),
  c("She took", ""),
  c("They (singular formal) took", ""),
  c("It took", ""),
  c("We took", ""),
  c("You (plural) took", ""),
  c("They (people) took", ""),
  c("They (objects) took", ""),
  c("I killed", ""),
  c("You (informal) killed", ""),
  c("He killed", ""),
  c("She killed", ""),
  c("They (singular formal) killed", ""),
  c("It killed", ""),
  c("We killed", ""),
  c("You (plural) killed", ""),
  c("They (people) killed", ""),
  c("They (objects) killed", ""),
  c("I did", ""),
  c("You (informal) did", ""),
  c("He did", ""),
  c("She did", ""),
  c("They (singular formal) did", ""),
  c("It did", ""),
  c("We did", ""),
  c("You (plural) did", ""),
  c("They (people) did", ""),
  c("They (objects) did", "")
)