past_tense_verbs <- list(
  c("I bought", "வாங்கினேன்"),
  c("You (informal) bought", "வாங்கினாய்"),
  c("He bought", "வாங்கினான்"),
  c("She bought", "வாங்கினாள்"),
  c("They (singular formal) bought", "வாங்கினார்"),
  c("It bought", "வாங்கினது"),
  c("We bought", "வாங்கினோம்"),
  c("You (plural) bought", "வாங்கினீர்கள்"),
  c("They (people) bought", "வாங்கினனர்"),
  c("They (objects) bought", "வாங்கினன"),
  c("I looked", "பார்த்தேன்"),
  c("You (informal) looked", "பார்த்தாய்"),
  c("He looked", "பார்த்தான்"),
  c("She looked", "பார்த்தாள்"),
  c("They (singular formal) looked", "பார்த்தார்"),
  c("It looked", "பார்த்தது"),
  c("We looked", "பார்த்தோம்"),
  c("You (plural) looked", "பார்த்தீர்கள்"),
  c("They (people) looked", "பார்த்தனர்"),
  c("They (objects) looked", "பார்த்தன"),
  c("I squeezed", "பிழிந்தேன்"),
  c("You (informal) squeezed", "பிழிந்தாய்"),
  c("He squeezed", "பிழிந்தான்"),
  c("She squeezed", "பிழிந்தாள்"),
  c("They (singular formal) squeezed", "பிழிந்தார்"),
  c("It squeezed", "பிழிந்தது"),
  c("We squeezed", "பிழிந்தோம்"),
  c("You (plural) squeezed", "பிழிந்தீர்கள்"),
  c("They (people) squeezed", "பிழிந்தனர்"),
  c("They (objects) squeezed", "பிழிந்தன"),
  c("I was/sat", "இருந்தேன்"),
  c("You (informal) were/sat", "இருந்தாய்"),
  c("He was/sat", "இருந்தான்"),
  c("She was/sat", "இருந்தாள்"),
  c("They (singular formal) were/sat", "இருந்தார்"),
  c("It was/sat", "இருந்தது"),
  c("We were/sat", "இருந்தோம்"),
  c("You (plural) were/sat", "இருந்தீர்கள்"),
  c("They (people) were/sat", "இருந்தனர்"),
  c("They (objects) were/sat", "இருந்தன"),
  c("I ate", "சாப்பிட்டேன்"),
  c("You (informal) ate", "சாப்பிட்டாய்"),
  c("He ate", "சாப்பிட்டான்"),
  c("She ate", "சாப்பிட்டாள்"),
  c("They (singular formal) ate", "சாப்பிட்டார்"),
  c("It ate", "சாப்பிட்டது"),
  c("We ate", "சாப்பிட்டோம்"),
  c("You (plural) ate", "சாப்பிட்டீர்கள்"),
  c("They (people) ate", "சாப்பிட்டனர்"),
  c("They (objects) ate", "சாப்பிட்டன"),
  c("I sat", "உட்கார்ந்தேன்"),
  c("You (informal) sat", "உட்கார்ந்தாய்"),
  c("He sat", "உட்கார்ந்தான்"),
  c("She sat", "உட்கார்ந்தாள்"),
  c("They (singular formal) sat", "உட்கார்ந்தார்"),
  c("It sat", "உட்கார்ந்தது"),
  c("We sat", "உட்கார்ந்தோம்"),
  c("You (plural) sat", "உட்கார்ந்தீர்கள்"),
  c("They (people) sat", "உட்கார்ந்தனர்"),
  c("They (objects) sat", "உட்கார்ந்தன"),
  c("I fell", "விழுந்தேன்"),
  c("You (informal) fell", "விழுந்தாய்"),
  c("He fell", "விழுந்தான்"),
  c("She fell", "விழுந்தாள்"),
  c("They (singular formal) fell", "விழுந்தார்"),
  c("It fell", "விழுந்தது"),
  c("We fell", "விழுந்தோம்"),
  c("You (plural) fell", "விழுந்தீராகள்"),
  c("They (people) fell", "விழுந்தனர்"),
  c("They (objects) fell", "விழுந்தன"),
  c("I took", "கொண்டேன்"),
  c("You (informal) took", "கொண்டாய்"),
  c("He took", "கொண்டான்"),
  c("She took", "கொண்டாள்"),
  c("They (singular formal) took", "கொண்டார்"),
  c("It took", "கொண்டது"),
  c("We took", "கொண்டோம்"),
  c("You (plural) took", "கொண்டூர்கள்"),
  c("They (people) took", "கொண்டனர்"),
  c("They (objects) took", "கொண்டன"),
  c("I killed", "கொன்றேன்"),
  c("You (informal) killed", "கொன்றாய்"),
  c("He killed", "கொன்றான்"),
  c("She killed", "கொன்றாள்"),
  c("They (singular formal) killed", "கொன்றார்"),
  c("It killed", "கொன்றது"),
  c("We killed", "கொன்றோம்"),
  c("You (plural) killed", "கொன்றீர்கள்"),
  c("They (people) killed", "கொன்றனர்"),
  c("They (objects) killed", "கொன்றன"),
  c("I did", "செய்தேன்"),
  c("You (informal) did", "செய்தாய்"),
  c("He did", "செய்தான்"),
  c("She did", "செய்தாள்"),
  c("They (singular formal) did", "செய்தார்"),
  c("It did", "செய்தது"),
  c("We did", "செய்தோம்"),
  c("You (plural) did", "செய்தீராகள்"),
  c("They (people) did", "செய்தனர்"),
  c("They (objects) did", "செய்தன")
) %>%
  map(~ {
    .x[1] = paste0("[Verbs in the Perfect Past tense] ", .x[1]) # prepend question type
    .x
  })