present_tense_verbs <- list(
  c("I am buying", "வாங்குகிறேன்"),
  c("You (informal) are buying", "வாங்குகிறாய்"),
  c("He (informal) is buying", "வாங்குகிறான்"),
  c("She (informal) is buying", "வாங்குகிறாள்"),
  c("They (singular formal) are buying", "வாங்குகிறார்"),
  c("It is buying", "வாங்குகிறது"),
  c("We are buying", "வாங்குகிறோம்"),
  c("You (plural) are buying", "வாங்குகிறீர்கள்"),
  c("They (people) are buying", "வாங்குகிறனர்"),
  c("They (objects) are buying", "வாங்குகிறன"),
  c("I am looking", "பார்க்கிறேன்"),
  c("You (informal) are looking", "பார்க்கிறாய்"),
  c("He (informal) is looking", "பார்க்கிறான்"),
  c("She (informal) is looking", "பார்க்கிறாள்"),
  c("They (singular formal) are looking", "பார்க்கிறார்"),
  c("It is looking", "பார்க்கிறது"),
  c("We are looking", "பார்க்கிறோம்"),
  c("You (plural) are looking", "பார்க்கிறீர்கள்"),
  c("They (people) are looking", "பார்க்கிறளனர்"),
  c("They (objects) are looking", "பார்க்கிறன"),
  c("I am squeezing", "பிழிகிறேன்"),
  c("You (informal) are squeezing", "பிழிகிறாய்"),
  c("He is squeezing", "பிழிகிறான்"),
  c("She is squeezing", "பிழிகிறாள்"),
  c("They (singular formal) are squeezing", "பிழிகிறார்"),
  c("It is squeezing", "பிழிகிறது"),
  c("We are squeezing", "பிழிகிறோம்"),
  c("You (plural) are squeezing", "பிழிகிறீர்கள்"),
  c("They (people) are squeezing", "பிழிகிறனர்"),
  c("They (objects) are squeezing", "பிழிகிறன"),
  c("I am being/sitting", "இருக்கிறேன்"),
  c("You (informal) are being/sitting", "இருக்கிறாய்"),
  c("He is being/sitting", "இருக்கிறான்"),
  c("She is being/sitting", "இருக்கிறாள்"),
  c("They (singular formal) are being/sitting", "இருக்கிறார்"),
  c("It is being/sitting", "இருக்கிறது"),
  c("We are being/sitting", "இருக்கிறோம்"),
  c("You (plural) are being/sitting", "இருக்கிறீர்கள்"),
  c("They (people) are being/sitting", "இருக்கிறனர்"),
  c("They (objects) are being/sitting", "இருக்கிறன"),
  c("I am eating", "சாப்பிடுகிறேன்"),
  c("You (informal) are eating", "சாப்பிடுகிறாய்"),
  c("He is eating", "சாப்பிடுகிறான்"),
  c("She is eating", "சாப்பிடுகிறாள்"),
  c("They (singular formal) are eating", "சாப்பிடுகிறார்"),
  c("It is eating", "சாப்பிடுகிறது"),
  c("We are eating", "சாப்பிடுகிறோம்"),
  c("You (plural) are eating", "சாப்பிடுகிறீர்கள்"),
  c("They (people) are eating", "சாப்பிடுகிறனர்"),
  c("They (objects) are eating", "சாப்பிடுகிறன"),
  c("I am sitting", "உட்கார்கிறேன்"),
  c("You (informal) are sitting", "உட்கார்கிறாய்"),
  c("He is sitting", "உட்கார்கிறான்"),
  c("She is sitting", "உட்கார்கிறாள்"),
  c("They (singular formal) is sitting", "உட்கார்கிறார்"),
  c("It is sitting", "உட்கார்கிறது"),
  c("We are sitting", "உட்கார்கிறோம்"),
  c("You (plural) are sitting", "உட்கார்கிறீர்கள்"),
  c("They (people) are sitting", "உட்கார்கிறனர்"),
  c("They (objects) are sitting", "உட்கார்கிறன"),
  c("I am falling", "விழுகிறேன்"),
  c("You (informal) are falling", "விழுகிறாய்"),
  c("He is falling", "விழுகிறான்"),
  c("She is falling", "விழுகிறாள்"),
  c("They (singular formal) are falling", "விழுகிறார்"),
  c("It is falling", "விழுகிறது"),
  c("We are falling", "விழுகிறோம்"),
  c("You (plural) are falling", "விழுகிறீர்கள்"),
  c("They (people) are falling", "விழுகிறனர்"),
  c("They (objects) are falling", "விழுகிறன"),
  c("I am taking", "கொள்கிறேன்"),
  c("You (informal) are taking", "கொள்கிறாய்"),
  c("He is taking", "கொள்கிறான்"),
  c("She is taking", "கொள்கிறாள்"),
  c("They (singular formal) are taking", "கொள்கிறார்"),
  c("It is taking", "கொள்கிறது"),
  c("We are taking", "கொள்கிறோம்"),
  c("You (plural) are taking", "கொள்கிறீர்கள்"),
  c("They (people) are taking", "கொள்கிறனர்"),
  c("They (objects) are taking", "கொள்கிறன"),
  c("I am killing", "கொல்கிறேன்"),
  c("You (informal) are killing", "கொல்கிறாய்"),
  c("He is killing", "கொல்கிறான்"),
  c("She is killing", "கொல்கிறாள்"),
  c("They (singular formal) are killing", "கொல்கிறார்"),
  c("It is killing", "கொல்கிறது"),
  c("We are killing", "கொல்கிறோம்"),
  c("You (plural) are killing", "கொல்கிறீர்கள்"),
  c("They (people) are killing", "கொல்கிறனர்"),
  c("They (objects) are killing", "கொல்கிறன"),
  c("I am doing", "செய்கிறேன்"),
  c("You (informal) are doing", "செய்கிறாய்"),
  c("He is doing", "செய்கிறான்"),
  c("She is doing", "செய்கிறாள்"),
  c("They (singular formal) are doing", "செய்கிறார்"),
  c("It is doing", "செய்கிறது"),
  c("We are doing", "செய்கிறோம்"),
  c("You (plural) are doing", "செய்கிறீர்கள்"),
  c("They (people) are doing", "செய்கிறனர்"),
  c("They (objects) are doing", "செய்கிறன")
)