present_tense_verbs <- list(
  c("I am buying", "வாங்குகிறேன்"),
  c("You (informal) are buying", "வாங்குகிறாய்"),
  c("He (informal) is buying", "வாங்குகிறான்"),
  c("She (informal) is buying", "வாங்குகிறாள்"),
  c("They (singular formal) are buying", "வாங்குகிறார்"),
  c("It is buying", "வாங்குகிறது"),
  c("We are buying", "வாங்குகிறோம்"),
  c("You (plural) are buying", "வாங்குகிறீர்கள்"),
  c("They (people) are buying", "வாங்குகிறனர்"),
  c("They (objects) are buying", "வாங்குகிறன"),
  c("I am looking", ""),
  c("You (informal) are looking", ""),
  c("He (informal) is looking", ""),
  c("She (informal) is looking", ""),
  c("They (singular formal) are looking", ""),
  c("It is looking", ""),
  c("We are looking", ""),
  c("You (plural) are looking", ""),
  c("They (people) are looking", ""),
  c("They (objects) are looking", ""),
  c("I am squeezing", ""),
  c("You (informal) are squeezing", ""),
  c("He is squeezing", ""),
  c("She is squeezing", ""),
  c("They (singular formal) are squeezing", ""),
  c("It is squeezing", ""),
  c("We are squeezing", ""),
  c("You (plural) are squeezing", ""),
  c("They (people) are squeezing", ""),
  c("They (objects) are squeezing", ""),
  c("I am being/sitting", ""),
  c("You (informal) are being/sitting", ""),
  c("He is being/sitting", ""),
  c("She is being/sitting", ""),
  c("They (singular formal) are being/sitting", ""),
  c("It is being/sitting", ""),
  c("We are being/sitting", ""),
  c("You (plural) are being/sitting", ""),
  c("They (people) are being/sitting", ""),
  c("They (objects) are being/sitting", ""),
  c("I am eating", ""),
  c("You (informal) are eating", ""),
  c("He is eating", ""),
  c("She is eating", ""),
  c("They (singular formal) is eating", ""),
  c("It is eating", ""),
  c("We are eating", ""),
  c("You (plural) are eating", ""),
  c("They (people) are eating", ""),
  c("They (objects) are eating", ""),
  c("I am sitting", ""),
  c("You (informal) are sitting", ""),
  c("He is sitting", ""),
  c("She is sitting", ""),
  c("They (singular formal) is sitting", ""),
  c("It is sitting", ""),
  c("We are sitting", ""),
  c("You (plural) are sitting", ""),
  c("They (people) are sitting", ""),
  c("They (objects) are sitting", ""),
  c("I am falling", ""),
  c("You (informal) are falling", ""),
  c("He is falling", ""),
  c("She is falling", ""),
  c("They (singular formal) are falling", ""),
  c("It is falling", ""),
  c("We are falling", ""),
  c("You (plural) are falling", ""),
  c("They (people) are falling", ""),
  c("They (objects) are falling", ""),
  c("I am taking", ""),
  c("You (informal) are taking", ""),
  c("He is taking", ""),
  c("She is taking", ""),
  c("They (singular formal) are taking", ""),
  c("It is taking", ""),
  c("We are taking", ""),
  c("You (plural) are taking", ""),
  c("They (people) are taking", ""),
  c("They (objects) are taking", ""),
  c("I am killing", ""),
  c("You (informal) are killing", ""),
  c("He is killing", ""),
  c("She is killing", ""),
  c("They (singular formal) are killing", ""),
  c("It is killing", ""),
  c("We are killing", ""),
  c("You (plural) are killing", ""),
  c("They (people) are killing", ""),
  c("They (objects) are killing", ""),
  c("I am doing", ""),
  c("You (informal) are doing", ""),
  c("He is doing", ""),
  c("She is doing", ""),
  c("They (singular formal) are doing", ""),
  c("It is doing", ""),
  c("We are doing", ""),
  c("You (plural) are doing", ""),
  c("They (people) are doing", ""),
  c("They (objects) are doing", "")
)